"""Authenticated, operation-guarded source-client boundary."""

from ntulearn_skill.client.contracts import (
    AuthenticationRequired,
    AuthorizedReadSession,
    CapabilityState,
    ContentSourceRecord,
    CourseSourceRecord,
    EphemeralByteStream,
    Page,
    PageRequest,
    PaginationCycle,
    PaginationLimitReached,
    ReadPolicyViolation,
    ReadPurpose,
    ResourceMetadataRecord,
    SessionExpired,
    SessionProvider,
    SessionStatus,
    SourceAccessDenied,
    SourceCapabilities,
    SourceCapability,
    SourceError,
    SourceProtocolError,
    SourceProvider,
    SourceUnavailable,
    UnsupportedCapability,
)
from ntulearn_skill.client.ntulearn import NtulearnSourceAdapter
from ntulearn_skill.client.transport import (
    ReadOnlyTransport,
    ReadOperation,
    ResolvedReadRequest,
    SafeReadRequest,
    WireResponse,
)

__all__ = [
    "AuthenticationRequired",
    "AuthorizedReadSession",
    "CapabilityState",
    "ContentSourceRecord",
    "CourseSourceRecord",
    "EphemeralByteStream",
    "NtulearnSourceAdapter",
    "Page",
    "PageRequest",
    "PaginationCycle",
    "PaginationLimitReached",
    "ReadOnlyTransport",
    "ReadOperation",
    "ReadPolicyViolation",
    "ReadPurpose",
    "ResolvedReadRequest",
    "ResourceMetadataRecord",
    "SafeReadRequest",
    "SessionExpired",
    "SessionProvider",
    "SessionStatus",
    "SourceAccessDenied",
    "SourceCapabilities",
    "SourceCapability",
    "SourceError",
    "SourceProtocolError",
    "SourceProvider",
    "SourceUnavailable",
    "UnsupportedCapability",
    "WireResponse",
]
